const wa="https://wa.me/5565999964842?text=Ol%C3%A1%2C%20Dra.%20Rejane.%20Gostaria%20de%20agendar%20um%20atendimento.";
const areas=[['01','Aposentadorias','Análise de requisitos, simulações e condução do pedido para uma decisão previdenciária mais segura.'],['02','Planejamento previdenciário','Estratégia individual para identificar o melhor momento e a modalidade adequada de aposentadoria.'],['03','Benefícios e revisões','BPC/LOAS, incapacidade, pensão por morte, revisões e recursos administrativos.'],['04','Direito tributário','Defesas, impugnações, regularização fiscal e parcelamentos para pessoas e empresas.'],['05','Consultoria empresarial','Planejamento tributário, análise de riscos e orientação preventiva para decisões de negócio.'],['06','Atuação estratégica','Diagnóstico técnico, plano de ação claro e acompanhamento transparente em todas as etapas.']];
export default function Home(){return <main>
<header className="header"><a className="brand" href="#topo"><span className="mark">R</span><span><b>REJANE</b><small>ADVOCACIA</small></span></a><nav className="nav"><a href="#escritorio">Escritório</a><a href="#atuacao">Atuação</a><a href="#advogada">Advogada</a><a href="#contato">Contato</a></nav><a className="outline" href="#contato">Agendar consulta</a><details className="menu"><summary><i/><i/></summary><nav><a href="#escritorio">Escritório</a><a href="#atuacao">Atuação</a><a href="#advogada">Advogada</a><a href="#contato">Contato</a></nav></details></header>
<section className="hero" id="topo"><div className="heroCopy"><p className="eyebrow">Atendimento em Mato Grosso e em todo o Brasil</p><h1>Decisões jurídicas mais seguras começam com uma estratégia <em>bem construída.</em></h1><p className="lead">Advocacia tributária e previdenciária com escuta atenta, análise individualizada e orientação clara para pessoas e empresas.</p><div className="actions"><a className="primary" href={wa}>Falar no WhatsApp <span>↗</span></a><a className="textLink" href="#atuacao">Conheça a atuação ↓</a></div><p className="trust">OAB/MT 29.296 · Atendimento presencial e online</p></div><div className="heroPhoto"><div><img src="/rejane-perfil.jpeg" alt="Dra. Rejane Maria Barros Silva"/></div><p><small>Advogada responsável</small><b>Rejane Maria Barros Silva</b></p></div></section>
<div className="strip"><span>Atuamos em</span><b>Direito Previdenciário</b><i/><b>Direito Tributário</b><i/><b>Consultoria Empresarial</b></div>
<section className="office section" id="escritorio"><div><p className="eyebrow dark">O escritório</p><h2>Rigor técnico com um atendimento verdadeiramente <em>próximo.</em></h2></div><div className="officeBody"><p>O escritório Rejane Advocacia atua de forma consultiva e contenciosa, traduzindo questões complexas em caminhos claros e responsáveis.</p><p>Cada caso recebe atenção individual, planejamento e acompanhamento transparente — do primeiro diagnóstico à conclusão.</p><div className="metrics"><div><b>02</b><span>áreas especializadas</span></div><div><b>100%</b><span>atendimento personalizado</span></div><div><b>BR</b><span>atuação em todo o Brasil</span></div></div></div></section>
<section className="areas section" id="atuacao"><div className="heading"><div><p className="eyebrow">Áreas de atuação</p><h2>Da dúvida à direção. Da análise à <em>decisão.</em></h2></div><p>Soluções pensadas para proteger direitos, reduzir riscos e trazer segurança em momentos importantes.</p></div><div className="areaGrid">{areas.map(a=><article key={a[0]}><span>{a[0]}</span><div><h3>{a[1]}</h3><p>{a[2]}</p></div><b>↗</b></article>)}</div></section>
<section className="profile section" id="advogada"><div className="profilePhoto"><img src="/rejane-perfil.jpeg" alt="Retrato profissional da Dra. Rejane"/></div><div className="profileCopy"><p className="eyebrow dark">Quem está à frente</p><h2>Rejane Maria<br/><em>Barros Silva.</em></h2><p className="role">Advogada · OAB/MT 29.296</p><blockquote>“A boa advocacia começa pela compreensão cuidadosa da realidade de cada cliente.”</blockquote><p>Mestre em Economia pela UFMT e pós-graduada em Direito Tributário e Previdenciário pela ESA Nacional. Sua atuação une conhecimento jurídico, visão econômica e atendimento humanizado.</p><ul><li>Mestre em Economia — UFMT</li><li>Pós-graduação em Direito Tributário e Previdenciário</li><li>Atendimento presencial em Diamantino/MT e online</li></ul></div></section>
<section className="method section"><div className="heading"><div><p className="eyebrow dark">Como funciona</p><h2>Clareza em cada <em>etapa.</em></h2></div></div><div className="steps"><article><span>01</span><h3>Você conta seu caso</h3><p>O primeiro contato é acolhedor, objetivo e totalmente sigiloso.</p></article><article><span>02</span><h3>Análise jurídica</h3><p>Documentos e possibilidades são avaliados com critério técnico.</p></article><article><span>03</span><h3>Plano de ação</h3><p>Você recebe orientação clara sobre caminhos, prazos e próximos passos.</p></article></div></section>
<section className="contact section" id="contato"><div><p className="eyebrow">Contato</p><h2>Vamos conversar sobre o seu <em>caso?</em></h2><p className="contactLead">Atendimento personalizado, sigiloso, presencial ou online.</p><div className="details"><a href="tel:+5565999964842"><small>Telefone e WhatsApp</small><b>(65) 99996-4842</b></a><a href="mailto:rejanesilva.advocacia@hotmail.com"><small>E-mail</small><b>rejanesilva.advocacia@hotmail.com</b></a><div><small>Endereço</small><b>Av. Des. J. P. F. Mendes, 544<br/>Centro · Diamantino/MT</b></div></div></div><form action={wa}><label>Nome<input placeholder="Seu nome" required/></label><label>WhatsApp<input placeholder="(00) 00000-0000" required/></label><label>Como podemos ajudar?<textarea placeholder="Conte brevemente o que você precisa" rows={4}/></label><button>Quero falar com a advogada <span>↗</span></button><p>Você será direcionado ao WhatsApp.</p></form></section>
<footer><div className="footerBrand"><span className="mark">R</span><div><b>REJANE ADVOCACIA</b><p>Estratégia jurídica. Atendimento próximo.</p></div></div><div><small>NAVEGAÇÃO</small><a href="#escritorio">Escritório</a><a href="#atuacao">Atuação</a><a href="#advogada">Advogada</a></div><div><small>CONTATO</small><a href="tel:+5565999964842">(65) 99996-4842</a><a href="mailto:rejanesilva.advocacia@hotmail.com">E-mail</a><a href={wa}>WhatsApp</a></div><p className="legal">© 2026 Rejane Advocacia. Conteúdo informativo, sem promessa de resultado.</p></footer><a className="whats" href={wa}>✦ <b>WhatsApp</b></a>
</main>}
